//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 02:47:10 PM CET 
//


package hu.uni.miskolc.iit.softwaretesting.dtoTypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bookInstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bookInstanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inventoryNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="book" type="{}bookType"/>
 *         &lt;element name="isLoaned" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookInstanceType", propOrder = {
    "inventoryNumber",
    "book",
    "isLoaned"
})
public class BookInstanceType {

    protected long inventoryNumber;
    @XmlElement(required = true)
    protected BookType book;
    protected boolean isLoaned;

    /**
     * Gets the value of the inventoryNumber property.
     * 
     */
    public long getInventoryNumber() {
        return inventoryNumber;
    }

    /**
     * Sets the value of the inventoryNumber property.
     * 
     */
    public void setInventoryNumber(long value) {
        this.inventoryNumber = value;
    }

    /**
     * Gets the value of the book property.
     * 
     * @return
     *     possible object is
     *     {@link BookType }
     *     
     */
    public BookType getBook() {
        return book;
    }

    /**
     * Sets the value of the book property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookType }
     *     
     */
    public void setBook(BookType value) {
        this.book = value;
    }

    /**
     * Gets the value of the isLoaned property.
     * 
     */
    public boolean isIsLoaned() {
        return isLoaned;
    }

    /**
     * Sets the value of the isLoaned property.
     * 
     */
    public void setIsLoaned(boolean value) {
        this.isLoaned = value;
    }

}
