//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 02:47:10 PM CET 
//


package hu.uni.miskolc.iit.softwaretesting.dtoTypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for borrowingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="borrowingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="borrowID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="reader" type="{}userType"/>
 *         &lt;element name="creationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="expirationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="borrowStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="BORROWED"/>
 *               &lt;enumeration value="REQUESTED"/>
 *               &lt;enumeration value="EXPIRED"/>
 *               &lt;enumeration value="RETURNED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bookInstance" type="{}bookInstanceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "borrowingType", propOrder = {
    "borrowID",
    "reader",
    "creationDate",
    "expirationDate",
    "borrowStatus",
    "bookInstance"
})
public class BorrowingType {

    protected long borrowID;
    @XmlElement(required = true)
    protected UserType reader;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expirationDate;
    @XmlElement(required = true)
    protected String borrowStatus;
    @XmlElement(required = true)
    protected BookInstanceType bookInstance;

    /**
     * Gets the value of the borrowID property.
     * 
     */
    public long getBorrowID() {
        return borrowID;
    }

    /**
     * Sets the value of the borrowID property.
     * 
     */
    public void setBorrowID(long value) {
        this.borrowID = value;
    }

    /**
     * Gets the value of the reader property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getReader() {
        return reader;
    }

    /**
     * Sets the value of the reader property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setReader(UserType value) {
        this.reader = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the borrowStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrowStatus() {
        return borrowStatus;
    }

    /**
     * Sets the value of the borrowStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrowStatus(String value) {
        this.borrowStatus = value;
    }

    /**
     * Gets the value of the bookInstance property.
     * 
     * @return
     *     possible object is
     *     {@link BookInstanceType }
     *     
     */
    public BookInstanceType getBookInstance() {
        return bookInstance;
    }

    /**
     * Sets the value of the bookInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookInstanceType }
     *     
     */
    public void setBookInstance(BookInstanceType value) {
        this.bookInstance = value;
    }

}
